name: "Test Build"

on: [pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Build container
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target babybuddy \
            --docker-hub ottpeterr
